name: qabella
description: A new Flutter project.


publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  #ios: true
  image_path: "assets/imgs/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/imgs/

  fonts:
    - family: Qabella
      fonts:
        - asset: assets/fonts/JF-Flat-Regular.ttf
